# Generated by Django 4.1.1 on 2022-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_last_login_remove_user_password_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="user",
        #     name="last_login",
        #     field=models.DateTimeField(
        #         blank=True, null=True, verbose_name="last login"
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="user",
        #     name="password",
        #     field=models.CharField(default=0, max_length=128, verbose_name="password"),
        #     preserve_default=False,
        # ),
    ]
