# Generated by Django 4.1.1 on 2022-10-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_account_user_alter_deposit_user_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=16, unique=True, verbose_name="자산 그룹"),
                ),
            ],
            options={
                "db_table": "assets_groups",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=30, verbose_name="종목명")),
                (
                    "ISIN",
                    models.CharField(max_length=12, unique=True, verbose_name="ISIN"),
                ),
                (
                    "current_price",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="현재가"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.assetgroup",
                    ),
                ),
            ],
            options={
                "db_table": "stocks",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="수량")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.stock"
                    ),
                ),
            ],
            options={
                "db_table": "assets",
            },
        ),
    ]
