# Generated by Django 4.1.1 on 2022-09-22 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=16, unique=True, verbose_name="자산 그룹"),
                ),
            ],
            options={
                "db_table": "assets_groups",
            },
        ),
        migrations.RemoveField(
            model_name="asset",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="asset_name",
        ),
        migrations.AddField(
            model_name="stock",
            name="current_price",
            field=models.PositiveIntegerField(default=0, verbose_name="현재가"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stock",
            name="ISIN",
            field=models.CharField(max_length=12, unique=True, verbose_name="ISIN"),
        ),
        migrations.AddField(
            model_name="stock",
            name="group",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.assetgroup",
            ),
            preserve_default=False,
        ),
    ]
